services:
  llm:
    image: ollama/ollama
    container_name: llm
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000

  backend:
    build:
      context: ./backend_langchain/backend_langchain
      dockerfile: Dockerfile
    container_name: cloud-agent-backend
    restart: always
    depends_on:
      - llm
      - chroma
    ports:
      - "8080:8080"
    environment:
      - LLM_URL=http://llm:11434/api/generate
      - CHROMA_URL=http://chroma:8000
      - AWS_REGION=eu-west-2
      - AWS_DEFAULT_REGION=eu-west-2
      # - ASSUME_ROLE_ARN=arn:aws:iam::<your_account_id>:role/<your_role>
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=
  ui:
    image: node:18
    container_name: cloud-agent-ui
    restart: always
    working_dir: /app
    volumes:
      - ./UI:/app
      - /app/node_modules
    command: bash -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - backend
